import {
  ALLOWED_IMAGE_REPOSITORIES,
  compareVersions,
  UPDATER_VERSION,
  type ReleaseManifest,
} from './domain.js';
import type {
  ProvenanceVerificationResult,
  ProvenanceVerifier,
} from './provenance.js';
import type { AgentRelease, ReleaseProvider } from './release.js';

export type ReleaseVerification = {
  release: AgentRelease;
  imageProvenance: ProvenanceVerificationResult[];
};

export async function verifyRelease(input: {
  version: string;
  releases: ReleaseProvider;
  provenance: ProvenanceVerifier;
}): Promise<ReleaseVerification> {
  const release = await input.releases.target(input.version);
  assertReleaseVerificationPolicy(release.manifest);
  return {
    release,
    imageProvenance: await verifyManifestImages(
      release.manifest,
      input.provenance,
    ),
  };
}

export function assertReleaseVerificationPolicy(manifest: ReleaseManifest) {
  if (manifest.requiresManualAction) throw new Error('REQUIRES_MANUAL_ACTION');
  if (manifest.supplyChain.attestationPolicy !== 'GITHUB_PROVENANCE_REQUIRED')
    throw new Error('LEGACY_RELEASE_MANUAL_REQUIRED');
  if (
    compareVersions(`v${UPDATER_VERSION}`, manifest.minimumUpdaterVersion) < 0
  )
    throw new Error('UPDATER_MAINTENANCE_REQUIRED');
}

export async function verifyManifestImages(
  manifest: ReleaseManifest,
  provenance: ProvenanceVerifier,
  imageRepositories: Record<
    'api' | 'web' | 'worker',
    string
  > = ALLOWED_IMAGE_REPOSITORIES,
): Promise<ProvenanceVerificationResult[]> {
  assertReleaseVerificationPolicy(manifest);
  const results: ProvenanceVerificationResult[] = [];
  for (const service of ['api', 'web', 'worker'] as const) {
    results.push(
      await verifyManifestImage(
        manifest,
        service,
        provenance,
        imageRepositories,
      ),
    );
  }
  return results;
}

export async function verifyManifestImage(
  manifest: ReleaseManifest,
  service: 'api' | 'web' | 'worker',
  provenance: ProvenanceVerifier,
  imageRepositories: Record<
    'api' | 'web' | 'worker',
    string
  > = ALLOWED_IMAGE_REPOSITORIES,
): Promise<ProvenanceVerificationResult> {
  assertReleaseVerificationPolicy(manifest);
  const repository = imageRepositories[service];
  if (manifest.images[service].repository !== repository)
    throw new Error(`REPOSITORY_MISMATCH_${service.toUpperCase()}`);
  return provenance.verify({
    service,
    repository,
    digest: manifest.images[service].digest,
    releaseTag: manifest.releaseTag,
    sourceCommit: manifest.sourceCommit,
  });
}

export function digestPinnedComposeOverride(verification: ReleaseVerification) {
  const { manifest } = verification.release;
  return [
    `# Authenticated PE Community ${verification.release.version} image identities.`,
    '# Generated by verify-release; use as the final Compose override.',
    'services:',
    ...(['api', 'web', 'worker'] as const).flatMap((service) => [
      `  ${service}:`,
      `    image: ${manifest.images[service].repository}@${manifest.images[service].digest}`,
    ]),
    '',
  ].join('\n');
}
